# permissions for end users to view markdownviews.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: markdown-view
    app.kubernetes.io/managed-by: kustomize
  name: markdownview-viewer-role
rules:
- apiGroups:
  - view.umechan.github.io
  resources:
  - markdownviews
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - view.umechan.github.io
  resources:
  - markdownviews/status
  verbs:
  - get
